### ISSUE TITLE
関数 `appear` の命名

### ISSUE THREAD

**Issue by naru-jpn** [Handii-inc/HDBubbleTransition#7]
https://github.com/Handii-inc/HDBubbleTransition/blob/master/HDBubbleTransition/Classes/HDBubbleTransition.swift#L42

細かいですが、 `with withDuration` と `with` が重複していましたので以下でいかがでしょう。

```swift
public static func appear(from center: CGPoint,
                              in bounds: CGRect,
                              with duration: Double,
                              colored bubbleColor: UIColor) -> UIViewControllerAnimatedTransitioning
```

`disappear` も同様です 🙏 

https://github.com/Handii-inc/HDBubbleTransition/blob/master/HDBubbleTransition/Classes/HDBubbleTransition.swift#L59

**Comment by IgnorantCoder** [comment]
@naru-jpn 
こちらなんですが引数が多いため減らそうかなと思ってるインターフェースでもあります。
FluentインターフェースなBuilderってswiftではどうですか？
例えば、

```swift
let bubble = Bubble.appear()
                   .from(somePoint)
                   .inside(someBounds)
                   .with(duration: 0.5)
                   .colored(.red)
return HDBubbleTransition(with: bubble)
```
のような感じです。

**Comment by IgnorantCoder** [comment]
いや、
```swift
HDBubbleTransition.colored(.red)
                  .appear(from: somePoint,
                                inside: someBounds,
                                with: 0.5)
```
が一番読みやすいか…？

**Comment by naru-jpn** [comment]
@IgnorantCode
読みやすさは後者の方がよいかと！

AutoLayout系のライブラリで見かける気がしますね。レイアウト系のライブラリではコード量を減らすのが目的だったりしますので、はじめから簡潔に書けるのであればどちらでもよいのかなと思います！
(個人的には標準のUIKitと同じように書けるのが1番学習コストが少ないので好みです)
